Areas/Admin/Models/Class1.cs
using System;

namespace MovieApp.Areas.Admin.Models;

public class Class1
{

}

Models/AppSetting.cs
using System;

namespace MovieApp.Models;

public class AppSetting
{
  public int Id { get; set; }
  public string? BrandName { get; set; }
  public string? HeroTitle { get; set; }
  public string? HeroSubTitle { get; set; }
  public string? HeroImgURL { get; set; }
}

Models/Category.cs
using System;

namespace MovieApp.Models;

public class Category
{
  public int CategoryId { get; set; }
  public string? CategoryName { get; set; }
}

Models/Contact.cs
using System;

namespace MovieApp.Models;

public class Contact
{
  public int Id { get; set; }
  public string? Name { get; set; }
  public string? Email { get; set; }
  public string? Subject { get; set; }
  public string? Message { get; set; }
  public DateTime SendingTime { get; set; }
  public int ContactId { get; set; }
}

Models/HomePageModel.cs
using System;


namespace MovieApp.Models;

public class HomePageModel
{
    public AppSetting? AppSetting { get; set; }
    public IEnumerable<Social>? Socials { get; set; }
    public IEnumerable<Movie>? Movies { get; set; }
    public IEnumerable<Category>? Categories { get; set; }
}

Models/Movie.cs
using System;

namespace MovieApp.Models;

public class Movie
{
  public int MovieId { get; set; }
  public int CategoryId { get; set; }
  public string? MovieName { get; set; }
  public int MovieDuration { get; set; }
  public string? AboutMovie { get; set; }
  public string? Director { get; set; }
  public string? Writer { get; set; }
  public string? Star { get; set; }
  public int ImdbPoint { get; set; }
  public string? MovieImgURL { get; set; }
  public string? MovieURL { get; set; }
  public string? WatchUrl { get; set; }
}

Models/Social.cs
using System;

namespace MovieApp.Models;

public class Social
{
  public int Id { get; set; }
  public string? SocialName { get; set; }
  public string? SocialUrl { get; set; }
  public string? SocialIcon { get; set; }
}

Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }

    }
}

Controllers/CategoryController.cs
using System.Data.SqlClient;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieApp.Models;

namespace MovieApp.Controllers
{

    public class CategoryController : Controller
    {
        private readonly string connectionString = "Server=localhost,1441;Database=PopcornViews;User=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=true;";
        // CharSet=utf8mb4;
        public async Task<IEnumerable<Movie>> GetMoviesByCategory(int categoryId)
        {
            using (var connection = new SqlConnection(connectionString))
            {
                var queryMovie = "SELECT * FROM Movies WHERE CategoryId = @CategoryId;";
                return await connection.QueryAsync<Movie>(queryMovie, new { CategoryId = categoryId });
            }
        }

        public async Task<IActionResult> Aksiyon()
        {
            var moviesaksiyon = await GetMoviesByCategory(1);
            return View(moviesaksiyon);
        }

        public async Task<IActionResult> Komedi()
        {
            var movieskomedi = await GetMoviesByCategory(2);
            return View(movieskomedi);
        }

        public async Task<IActionResult> Drama()
        {
            var moviesdrama = await GetMoviesByCategory(3);
            return View(moviesdrama);
        }

        public async Task<IActionResult> Korku()
        {
            var movieskorku = await GetMoviesByCategory(4);
            return View(movieskorku);
        }

        public async Task<IActionResult> BilimKurgu()
        {
            var moviesbilim = await GetMoviesByCategory(5);
            return View(moviesbilim);
        }
    }
}

Controllers/DetayController.cs
using System.Data.SqlClient;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class DetayController : Controller
    {
        private readonly string connectionString = "Server=localhost,1441;Database=PopcornViews;User=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=true";

        private async Task<Movie> GetMovieById(int movieId)
        {
            using (var connection = new SqlConnection(connectionString))
            {
                var query = "SELECT * FROM Movies WHERE MovieId = @MovieId;";
                return await connection.QueryFirstOrDefaultAsync<Movie>(query, new { MovieId = movieId });
            }
        }

        public async Task<IActionResult> Index(int id)
        {
            Console.WriteLine($"Received id: {id}");

            var movie = await GetMovieById(id);

            if (movie == null)
            {
                Console.WriteLine($"No movie found for id: {id}");
                return NotFound("Film bulunamadı.");
            }

            return View(movie);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models;
using System.Data.SqlClient;
using Dapper;

namespace MovieApp.Controllers;




public class HomeController : Controller
{
    public async Task<IActionResult> Index()
    {
    var connectionString = "Server=localhost,1441;Database=PopcornViews;User=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=true";

        // Server = localhost,1441; Database = PopcornViews; User = SA; Password = YourStrong@Passw0rd; TrustServerCertificate = true
        var connection = new SqlConnection(connectionString);

        var queryAppSetting = "select * from AppSettings";
        var appSetting = (await connection.QueryAsync<AppSetting>(queryAppSetting)).First();

        var queryMovies = "select * from Movies";
        var movies = await connection.QueryAsync<Movie>(queryMovies);


        var querySocials = "select * from Socials";
        var socials = await connection.QueryAsync<Social>(querySocials);

        var queryCategory = "select * from Categories";
        var categories = await connection.QueryAsync<Category>(queryCategory);

        HomePageModel model = new HomePageModel()
        {
            AppSetting = appSetting,
            Movies = movies,
            Socials = socials,
            Categories = categories,
        };
        return View(model);
    }



}

Controllers/IletisimsController.cs
using System.Data.SqlClient;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieApp.Models;



namespace MovieApp.Controllers
{
    public class IletisimsController : Controller
    {
        
        public async Task<ActionResult> Index()
        {

            var connectionString = "Server=localhost,1441;Database=PopcornViews;User=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=true";

            var connection = new SqlConnection(connectionString);

            var queryContacts = "select * from Contacts";
            var contacts = await connection.QueryAsync<Contact>(queryContacts);
            
            return View(contacts);

        }

    }
}

Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

Areas/Admin/Views/Shared/_BackToTopPartial.cshtml
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

Areas/Admin/Views/Shared/_FooterPartial.cshtml
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
</footer><!-- End Footer -->

Areas/Admin/Views/Shared/_HeaderPartial.cshtml
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="~/Admin/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-check-circle text-success"></i>
              <div>
                <h4>Sit rerum fuga</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>2 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-info-circle text-primary"></i>
              <div>
                <h4>Dicta reprehenderit</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>4 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li>

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="~/Admin/assets/img/messages-1.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Maria Hudson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>4 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="~/Admin/assets/img/messages-2.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Anna Nelson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>6 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="~/Admin/assets/img/messages-3.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="#">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="~/Admin/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

Views/Category/Aksiyon.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Aksiyon";
}

<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>AKSİYON</h1>
                    <p class="mb-0">Aksiyon dolu filmlerle tanışın! Hızlı araba kovalamacalarından destansı dövüş
                        sahnelerine, soluk kesen maceraların içinde kaybolmaya hazır olun. Her sahnede kalbinizin hızla
                        atacağı bu kategoride, heyecan ve gerilim sizi bekliyor.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<section id="gallery" class="gallery section">
    <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div class="gallery-item h-100">
                        <img src="@item.MovieImgURL" class="img-fluid" alt="@item.MovieName"
                            style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="gallery-links d-flex align-items-center justify-content-center">
                            <a href="@item.MovieImgURL" title="@item.MovieName" class="glightbox preview-link">
                                <i class="bi bi-arrows-angle-expand"></i>
                            </a>
                            <a asp-action="Index" asp-controller="Detay" asp-route-id="@item.MovieId" class="details-link">
                                <i class="bi bi-link-45deg"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- End Gallery Item -->
            }
        </div>
    </div>
</section>

Views/Category/BilimKurgu.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "BilimKurgu";
}
<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>BİLİM KURGU</h1>
                    <p class="mb-0">Geleceğe, evrene ve bilinmeze doğru bir yolculuk! Bilim kurgunun büyüleyici
                        dünyasında teknolojik mucizeleri, alternatif gerçeklikleri ve sıra dışı hikayeleri keşfedin.
                        Hayal gücünüzün sınırlarını zorlayacak bir deneyime hazır olun.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="gallery" class="gallery section">
    <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div class="gallery-item h-100">
                        <img src="@item.MovieImgURL" class="img-fluid" alt="@item.MovieName"
                            style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="gallery-links d-flex align-items-center justify-content-center">
                            <a href="@item.MovieImgURL" title="@item.MovieName" class="glightbox preview-link">
                                <i class="bi bi-arrows-angle-expand"></i>
                            </a>
                            <a asp-action="Index" asp-controller="Detay" asp-route-id="@item.MovieId" class="details-link">
                                <i class="bi bi-link-45deg"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- End Gallery Item -->
            }
        </div>
    </div>
</section>

Views/Category/Drama.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Drama";
}

<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>DRAM</h1>
                    <p class="mb-0">Hayatın en derin duygularını keşfedeceğiniz dram filmleriyle ruhunuza dokunun. İnsan
                        ilişkileri, mücadeleler ve içsel yolculuklarla dolu bu yapımlar, izleyiciyi hikayenin bir
                        parçası haline getiriyor.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="gallery" class="gallery section">
    <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div class="gallery-item h-100">
                        <img src="@item.MovieImgURL" class="img-fluid" alt="@item.MovieName"
                            style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="gallery-links d-flex align-items-center justify-content-center">
                            <a href="@item.MovieImgURL" title="@item.MovieName" class="glightbox preview-link">
                                <i class="bi bi-arrows-angle-expand"></i>
                            </a>
                            <a asp-action="Index" asp-controller="Detay" asp-route-id="@item.MovieId" class="details-link">
                                <i class="bi bi-link-45deg"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- End Gallery Item -->
            }
        </div>
    </div>
</section>

Views/Category/Komedi.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Komedi";
}
<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>KOMEDİ</h1>
                    <p class="mb-0">Gülmeye doyamayacağınız komedi filmleriyle tanışın! Eğlenceli hikayeler, absürt
                        karakterler ve zekice esprilerle dolu bu filmler, sizi günün stresinden uzaklaştırıp yüzünüzde
                        kocaman bir tebessüm bırakacak.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="gallery" class="gallery section">
    <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div class="gallery-item h-100">
                        <img src="@item.MovieImgURL" class="img-fluid" alt="@item.MovieName"
                            style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="gallery-links d-flex align-items-center justify-content-center">
                            <a href="@item.MovieImgURL" title="@item.MovieName" class="glightbox preview-link">
                                <i class="bi bi-arrows-angle-expand"></i>
                            </a>
                            <a asp-action="Index" asp-controller="Detay" asp-route-id="@item.MovieId" class="details-link">
                                <i class="bi bi-link-45deg"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- End Gallery Item -->
            }
        </div>
    </div>
</section>

Views/Category/Korku.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Korku";
}

<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>KORKU</h1>
                    <p class="mb-0">Cesaretinizi toplayın ve korku dolu dünyalara adım atın! Tüylerinizi diken diken
                        edecek hikayeler, ürkütücü atmosferler ve beklenmedik anlarla dolu bu filmler, sizi gerilim ve
                        dehşetin sınırlarında bir yolculuğa çıkaracak. Gözlerinizi kapatmaya cesaret edebilir misiniz?
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="gallery" class="gallery section">
    <div class="container-fluid" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4 justify-content-center">
            @foreach (var item in Model)
            {
                <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                    <div class="gallery-item h-100">
                        <img src="@item.MovieImgURL" class="img-fluid" alt="@item.MovieName"
                            style="width: 100%; height: 100%; object-fit: cover;">
                        <div class="gallery-links d-flex align-items-center justify-content-center">
                            <a href="@item.MovieImgURL" title="@item.MovieName" class="glightbox preview-link">
                                <i class="bi bi-arrows-angle-expand"></i>
                            </a>
                            <a asp-action="Index" asp-controller="Detay" asp-route-id="@item.MovieId" class="details-link">
                                <i class="bi bi-link-45deg"></i>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Views/Shared/_HeaderPartial.cshtml
<header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

        <a asp-area="Views" asp-controller="Home" asp-action="Index"
            class="logo d-flex align-items-center me-auto me-xl-0">
            <i class="bi bi-film" style="color: #c59b00;"></i>
            <h1 class="sitename">PopcornViews</h1>
        </a>

        <nav id="navmenu" class="navmenu">
            <ul>
                <li><a asp-area="Views" asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
                <li class="dropdown"><a><span>KATEGORİLER</span><i class="bi bi-chevron-down toggle-dropdown"></i></a>
                    <ul>
                        <li><a asp-controller="Category" asp-action="Aksiyon">Aksiyon</a></li>
                        <li><a asp-controller="Category" asp-action="Komedi">Komedi</a></li>
                        <li><a asp-controller="Category" asp-action="Drama">Dram</a></li>
                        <li><a asp-controller="Category" asp-action="Korku">Korku</a></li>
                        <li><a asp-controller="Category" asp-action="BilimKurgu">Bilim Kurgu</a></li>
                    </ul>
                </li>
                <li><a asp-controller="Iletisims" asp-action="Index">İLETİŞİM</a></li>
                <!-- Login Modal Trigger -->
                <li><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal">GİRİŞ</a></li>
            </ul>
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>
        <div class="header-social-links">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>

    </div>
</header>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: black; color: white; border:  1px solid white;">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel"><i class="bi bi-film" style="color: #c59b00;"></i>PopcornViews
                </h5>
                       
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                    style="filter: invert(1);"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="loginEmail" class="form-label">E-Mail</label>
                        <input type="email" class="form-control" id="loginEmail" placeholder="Enter your email">
                    </div>
                    <div class="mb-3">
                        <label for="loginPassword" class="form-label">Sifre</label>
                        <input type="password" class="form-control" id="loginPassword"
                            placeholder="Enter your password">
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Beni Hatirla</label>
                    </div>
                    <button type="submit" class="btn btn-primary w-100 mt-3"
                        style="background-color: #c59b00; border-color: #c59b00;">Giris</button>
                </form>
            </div>
            
            ,
        </div>
    </div>
</div>

Views/Shared/_PreloaderPartial.cshtml
<div id="preloader">
    <div class="line"></div>
</div>

Views/Shared/_ScriptsPartial.cshtml
<!-- Vendor JS Files -->
<script src="~/ui/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/ui/vendor/php-email-form/validate.js"></script>
<script src="~/ui/vendor/aos/aos.js"></script>
<script src="~/ui/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/ui/vendor/swiper/swiper-bundle.min.js"></script>

<!-- Main JS File -->
<script src="~/ui/js/main.js"></script>

Views/Shared/_ScrollTopPartial.cshtml
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>